version: '3.2'

services:

  mingaby:
    restart: always
    build:
      dockerfile: Dockerfile
    networks:
      - mingasby
    ports:
      - 80:3000
      - 443:443

networks:
  mingasby:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24