version: '3.2'

services:

  mingaby:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mingas_mingaby_1
    hostname: mingas_mingaby_1
    networks:
      - mingasby
    ports:
      - 3000:3000

  nginx:
    restart: always
    image: nginx:1.23.1
    container_name: mingas_nginx_1
    hostname: mingas_nginx_1
    networks:
      - mingasby
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./host/:/etc/nginx/conf.d/:ro
      - ./src/ssl/:/ssl/:ro

networks:
  mingasby:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24