export const data = [
  {
    id: 1,
    name: 'Стольградный Газовщик № 5',
    data: 'сентябрь 2011 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_5.pdf',
  },
  {
    id: 2,
    name: 'Стольградный Газовщик № 6',
    data: 'декабрь 2011 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_6.pdf',
  },
  {
    id: 3,
    name: 'Стольградный Газовщик № 7',
    data: 'март 2012 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_7.pdf',
  },
  {
    id: 4,
    name: 'Стольградный Газовщик № 8',
    data: 'май 2012 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_8.pdf',
  },
  {
    id: 5,
    name: 'Стольградный Газовщик № 9',
    data: 'сентябрь 2012 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_9.pdf',
  },
  {
    id: 6,
    name: 'Стольградный Газовщик № 10',
    data: 'декабрь 2012 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_10.pdf',
  },
  {
    id: 7,
    name: 'Стольградный Газовщик № 11',
    data: 'март 2013 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_11.pdf',
  },
  {
    id: 8,
    name: 'Стольградный Газовщик № 12',
    data: 'май 2013 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_12.pdf',
  },
  {
    id: 9,
    name: 'Стольградный Газовщик № 13',
    data: 'август 2013 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_13.pdf',
  },
  {
    id: 10,
    name: 'Стольградный Газовщик № 14',
    data: 'ноябрь 2013 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_14.pdf',
  },
  {
    id: 11,
    name: 'Стольградный Газовщик № 15',
    data: 'декабрь 2013 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_15.pdf',
  },
  {
    id: 12,
    name: 'Стольградный Газовщик № 16',
    data: 'март 2014 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_16.pdf',
  },
  {
    id: 13,
    name: 'Стольградный Газовщик № 17',
    data: 'май 2014 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_17.pdf',
  },
  {
    id: 14,
    name: 'Стольградный Газовщик № 18',
    data: 'октябрь 2014 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_18.pdf',
  },
  {
    id: 15,
    name: 'Стольградный Газовщик № 19',
    data: 'декабрь 2014 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_19.pdf',
  },
  {
    id: 16,
    name: 'Столичный Газовик № 20',
    data: 'апрель 2015 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_20.pdf',
  },
  {
    id: 19,
    name: 'Столичный Газовик № 23',
    data: 'декабрь 2015 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_23.pdf',
  },
  {
    id: 20,
    name: 'Столичный Газовик № 24',
    data: 'апрель 2016 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_24.pdf',
  },
  {
    id: 21,
    name: 'Столичный Газовик № 25',
    data: 'сентябрь 2016 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_25.pdf',
  },
  {
    id: 22,
    name: 'Столичный Газовик № 26',
    data: 'декабрь 2016 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_26.pdf',
  },
  {
    id: 23,
    name: 'Столичный Газовик № 27',
    data: 'март 2017 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_27.pdf',
  },
  {
    id: 24,
    name: 'Столичный Газовик № 28',
    data: 'май 2017 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_28.pdf',
  },
  {
    id: 25,
    name: 'Столичный Газовик № 29',
    data: 'август 2017 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_29.pdf',
  },
  {
    id: 26,
    name: 'Столичный Газовик № 30',
    data: 'декабрь 2017 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_30.pdf',
  },
  {
    id: 27,
    name: 'Столичный Газовик № 31',
    data: 'март 2018 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_31.pdf',
  },
  {
    id: 28,
    name: 'Столичный Газовик № 32',
    data: 'май 2018 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_32.pdf',
  },
  {
    id: 29,
    name: 'Столичный Газовик № 33',
    data: 'август 2018 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_33.pdf',
  },
  {
    id: 30,
    name: 'Столичный Газовик № 34',
    data: 'декабрь 2018 г.',
    link: 'https://back.mingas.by/public/newspapers/gazeta_34.pdf',
  },
];
